[package]
name = "gridworld-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
nom = ">=8.0.0"
rfd = "0.15.4"
serde = { version = ">=1.0.226", features = ["derive"] }
serde_json = "1.0"

ctrlc = "3.4"
